version: '3.8'

services:
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_bigdata_lab
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigdata_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_lab:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./"data":/data_import
    restart: unless-stopped

volumes:
  postgres_data_lab: